// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Orión.Infrastructure.Persistence;

#nullable disable

namespace Orión.Infrastructure.Migrations
{
    [DbContext(typeof(OrionDbContext))]
    partial class OrionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Orión.Domain.Entities.Componente", b =>
                {
                    b.Property<string>("IdComponente")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("ID_Componente");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("Activo");

                    b.Property<string>("EspecificacionesTecnicas")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Especificaciones_Tecnicas");

                    b.Property<DateTime?>("FechaUltimoCambio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Fecha_Ultimo_Cambio");

                    b.Property<int>("IdEstado")
                        .HasColumnType("integer")
                        .HasColumnName("ID_Estado");

                    b.Property<string>("IdMaquinaria")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("ID_Maquinaria");

                    b.Property<int>("IdTipoComponente")
                        .HasColumnType("integer")
                        .HasColumnName("ID_TipoComponente");

                    b.Property<string>("Marca")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Marca");

                    b.Property<string>("NombreComponente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Nombre_Componente");

                    b.Property<string>("NumeroSerie")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Numero_Serie");

                    b.HasKey("IdComponente");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdMaquinaria");

                    b.HasIndex("IdTipoComponente");

                    b.ToTable("Componente", (string)null);
                });

            modelBuilder.Entity("Orión.Domain.Entities.EstadoComponente", b =>
                {
                    b.Property<int>("IdEstado")
                        .HasColumnType("integer")
                        .HasColumnName("ID_Estado");

                    b.Property<string>("DescripcionEstado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Descripcion_Estado");

                    b.HasKey("IdEstado");

                    b.HasIndex("DescripcionEstado")
                        .IsUnique();

                    b.ToTable("EstadoComponente", (string)null);

                    b.HasData(
                        new
                        {
                            IdEstado = 1,
                            DescripcionEstado = "Activo"
                        },
                        new
                        {
                            IdEstado = 2,
                            DescripcionEstado = "En reparacion"
                        },
                        new
                        {
                            IdEstado = 3,
                            DescripcionEstado = "Dado de baja"
                        },
                        new
                        {
                            IdEstado = 4,
                            DescripcionEstado = "En stock"
                        });
                });

            modelBuilder.Entity("Orión.Domain.Entities.EstadoSolicitud", b =>
                {
                    b.Property<int>("IdEstadoSolicitud")
                        .HasColumnType("integer")
                        .HasColumnName("ID_EstadoSolicitud");

                    b.Property<string>("DescripcionEstado")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("Descripcion_Estado");

                    b.HasKey("IdEstadoSolicitud");

                    b.HasIndex("DescripcionEstado")
                        .IsUnique();

                    b.ToTable("EstadoSolicitud", (string)null);

                    b.HasData(
                        new
                        {
                            IdEstadoSolicitud = 1,
                            DescripcionEstado = "Abierta"
                        },
                        new
                        {
                            IdEstadoSolicitud = 2,
                            DescripcionEstado = "En proceso"
                        },
                        new
                        {
                            IdEstadoSolicitud = 3,
                            DescripcionEstado = "Esperando proveedor"
                        },
                        new
                        {
                            IdEstadoSolicitud = 4,
                            DescripcionEstado = "Finalizada"
                        },
                        new
                        {
                            IdEstadoSolicitud = 5,
                            DescripcionEstado = "Cancelada"
                        });
                });

            modelBuilder.Entity("Orión.Domain.Entities.Maquinaria", b =>
                {
                    b.Property<string>("IdMaquinaria")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("ID_Maquinaria");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("Activo");

                    b.Property<DateTime?>("FechaInstalacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Fecha_Instalacion");

                    b.Property<int>("IdNivelCritico")
                        .HasColumnType("integer")
                        .HasColumnName("ID_NivelCritico");

                    b.Property<int>("IdUbicacion")
                        .HasColumnType("integer")
                        .HasColumnName("ID_Ubicacion");

                    b.Property<string>("Marca")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Marca");

                    b.Property<string>("Modelo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Modelo");

                    b.Property<string>("NombreMaquina")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Nombre_Maquina");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Tipo");

                    b.HasKey("IdMaquinaria");

                    b.HasIndex("IdNivelCritico");

                    b.HasIndex("IdUbicacion");

                    b.ToTable("Maquinaria", (string)null);
                });

            modelBuilder.Entity("Orión.Domain.Entities.NivelCritico", b =>
                {
                    b.Property<int>("IdNivelCritico")
                        .HasColumnType("integer")
                        .HasColumnName("ID_NivelCritico");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Descripcion");

                    b.HasKey("IdNivelCritico");

                    b.HasIndex("Descripcion")
                        .IsUnique();

                    b.ToTable("NivelCritico", (string)null);

                    b.HasData(
                        new
                        {
                            IdNivelCritico = 1,
                            Descripcion = "Baja"
                        },
                        new
                        {
                            IdNivelCritico = 2,
                            Descripcion = "Media"
                        },
                        new
                        {
                            IdNivelCritico = 3,
                            Descripcion = "Alta"
                        },
                        new
                        {
                            IdNivelCritico = 4,
                            Descripcion = "Critico"
                        });
                });

            modelBuilder.Entity("Orión.Domain.Entities.SolicitudServicio", b =>
                {
                    b.Property<int>("IdSS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_SS");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("IdSS"));

                    b.Property<string>("DescripcionFalla")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Descripcion_Falla");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Fecha_Apertura");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Fecha_Cierre");

                    b.Property<int>("IdEstadoSolicitud")
                        .HasColumnType("integer")
                        .HasColumnName("ID_EstadoSolicitud");

                    b.Property<string>("IdMaquinaria")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("ID_Maquinaria");

                    b.Property<int?>("IdPersonal")
                        .HasColumnType("integer")
                        .HasColumnName("ID_Personal");

                    b.Property<int>("IdTipoMantto")
                        .HasColumnType("integer")
                        .HasColumnName("ID_TipoMantto");

                    b.HasKey("IdSS");

                    b.HasIndex("IdEstadoSolicitud");

                    b.HasIndex("IdMaquinaria");

                    b.HasIndex("IdPersonal");

                    b.HasIndex("IdTipoMantto");

                    b.ToTable("Solicitud_Servicio", (string)null);
                });

            modelBuilder.Entity("Orión.Domain.Entities.Tecnico", b =>
                {
                    b.Property<int>("IdPersonal")
                        .HasColumnType("integer")
                        .HasColumnName("ID_Personal");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("Activo");

                    b.Property<string>("Especialidad")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Especialidad");

                    b.Property<int>("IdTurno")
                        .HasColumnType("integer")
                        .HasColumnName("ID_Turno");

                    b.Property<string>("NombreApellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Nombre_Apellido");

                    b.HasKey("IdPersonal");

                    b.HasIndex("IdTurno");

                    b.ToTable("Tecnico", (string)null);
                });

            modelBuilder.Entity("Orión.Domain.Entities.TipoComponente", b =>
                {
                    b.Property<int>("IdTipoComponente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_TipoComponente");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("IdTipoComponente"));

                    b.Property<string>("NombreTipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("Nombre_Tipo");

                    b.HasKey("IdTipoComponente");

                    b.HasIndex("NombreTipo")
                        .IsUnique();

                    b.ToTable("TipoComponente", (string)null);
                });

            modelBuilder.Entity("Orión.Domain.Entities.TipoMantenimiento", b =>
                {
                    b.Property<int>("IdTipoMantto")
                        .HasColumnType("integer")
                        .HasColumnName("ID_TipoMantto");

                    b.Property<string>("DescripcionTipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Descripcion_Tipo");

                    b.HasKey("IdTipoMantto");

                    b.HasIndex("DescripcionTipo")
                        .IsUnique();

                    b.ToTable("TipoMantenimiento", (string)null);

                    b.HasData(
                        new
                        {
                            IdTipoMantto = 1,
                            DescripcionTipo = "Preventivo"
                        },
                        new
                        {
                            IdTipoMantto = 2,
                            DescripcionTipo = "Correctivo"
                        });
                });

            modelBuilder.Entity("Orión.Domain.Entities.Turno", b =>
                {
                    b.Property<int>("IdTurno")
                        .HasColumnType("integer")
                        .HasColumnName("ID_Turno");

                    b.Property<string>("DescripcionTurno")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Descripcion_Turno");

                    b.HasKey("IdTurno");

                    b.HasIndex("DescripcionTurno")
                        .IsUnique();

                    b.ToTable("Turno", (string)null);

                    b.HasData(
                        new
                        {
                            IdTurno = 1,
                            DescripcionTurno = "Matutino"
                        },
                        new
                        {
                            IdTurno = 2,
                            DescripcionTurno = "Vespertino"
                        },
                        new
                        {
                            IdTurno = 3,
                            DescripcionTurno = "Nocturno"
                        },
                        new
                        {
                            IdTurno = 4,
                            DescripcionTurno = "Mixto"
                        });
                });

            modelBuilder.Entity("Orión.Domain.Entities.Ubicacion", b =>
                {
                    b.Property<int>("IdUbicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_Ubicacion");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("IdUbicacion"));

                    b.Property<int>("NumeroNave")
                        .HasColumnType("integer")
                        .HasColumnName("Numero_Nave");

                    b.HasKey("IdUbicacion");

                    b.HasIndex("NumeroNave")
                        .IsUnique();

                    b.ToTable("Ubicacion", (string)null);
                });

            modelBuilder.Entity("Orión.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_Usuario");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("Activo");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Email");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Fecha_Creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Nombre_Usuario");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Password_Hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Rol");

                    b.HasKey("IdUsuario");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Orión.Domain.Entities.Componente", b =>
                {
                    b.HasOne("Orión.Domain.Entities.EstadoComponente", "EstadoComponente")
                        .WithMany("Componentes")
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Componente_EstadoComponente");

                    b.HasOne("Orión.Domain.Entities.Maquinaria", "Maquinaria")
                        .WithMany("Componentes")
                        .HasForeignKey("IdMaquinaria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Componente_Maquinaria");

                    b.HasOne("Orión.Domain.Entities.TipoComponente", "TipoComponente")
                        .WithMany("Componentes")
                        .HasForeignKey("IdTipoComponente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Componente_TipoComponente");

                    b.Navigation("EstadoComponente");

                    b.Navigation("Maquinaria");

                    b.Navigation("TipoComponente");
                });

            modelBuilder.Entity("Orión.Domain.Entities.Maquinaria", b =>
                {
                    b.HasOne("Orión.Domain.Entities.NivelCritico", "NivelCritico")
                        .WithMany("Maquinarias")
                        .HasForeignKey("IdNivelCritico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Maquinaria_NivelCritico");

                    b.HasOne("Orión.Domain.Entities.Ubicacion", "Ubicacion")
                        .WithMany("Maquinarias")
                        .HasForeignKey("IdUbicacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Maquinaria_Ubicacion");

                    b.Navigation("NivelCritico");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("Orión.Domain.Entities.SolicitudServicio", b =>
                {
                    b.HasOne("Orión.Domain.Entities.EstadoSolicitud", "EstadoSolicitud")
                        .WithMany("SolicitudesServicio")
                        .HasForeignKey("IdEstadoSolicitud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Solicitud_EstadoSolicitud");

                    b.HasOne("Orión.Domain.Entities.Maquinaria", "Maquinaria")
                        .WithMany("SolicitudesServicio")
                        .HasForeignKey("IdMaquinaria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Solicitud_Maquinaria");

                    b.HasOne("Orión.Domain.Entities.Tecnico", "Tecnico")
                        .WithMany("SolicitudesServicio")
                        .HasForeignKey("IdPersonal")
                        .HasConstraintName("FK_Solicitud_Tecnico");

                    b.HasOne("Orión.Domain.Entities.TipoMantenimiento", "TipoMantenimiento")
                        .WithMany("SolicitudesServicio")
                        .HasForeignKey("IdTipoMantto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Solicitud_TipoMantenimiento");

                    b.Navigation("EstadoSolicitud");

                    b.Navigation("Maquinaria");

                    b.Navigation("Tecnico");

                    b.Navigation("TipoMantenimiento");
                });

            modelBuilder.Entity("Orión.Domain.Entities.Tecnico", b =>
                {
                    b.HasOne("Orión.Domain.Entities.Turno", "Turno")
                        .WithMany("Tecnicos")
                        .HasForeignKey("IdTurno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Tecnico_Turno");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("Orión.Domain.Entities.EstadoComponente", b =>
                {
                    b.Navigation("Componentes");
                });

            modelBuilder.Entity("Orión.Domain.Entities.EstadoSolicitud", b =>
                {
                    b.Navigation("SolicitudesServicio");
                });

            modelBuilder.Entity("Orión.Domain.Entities.Maquinaria", b =>
                {
                    b.Navigation("Componentes");

                    b.Navigation("SolicitudesServicio");
                });

            modelBuilder.Entity("Orión.Domain.Entities.NivelCritico", b =>
                {
                    b.Navigation("Maquinarias");
                });

            modelBuilder.Entity("Orión.Domain.Entities.Tecnico", b =>
                {
                    b.Navigation("SolicitudesServicio");
                });

            modelBuilder.Entity("Orión.Domain.Entities.TipoComponente", b =>
                {
                    b.Navigation("Componentes");
                });

            modelBuilder.Entity("Orión.Domain.Entities.TipoMantenimiento", b =>
                {
                    b.Navigation("SolicitudesServicio");
                });

            modelBuilder.Entity("Orión.Domain.Entities.Turno", b =>
                {
                    b.Navigation("Tecnicos");
                });

            modelBuilder.Entity("Orión.Domain.Entities.Ubicacion", b =>
                {
                    b.Navigation("Maquinarias");
                });
#pragma warning restore 612, 618
        }
    }
}
